// app/components/Link.vue
<script setup lang="ts">
const {
  link,
  text,
  external = false,
  active = false,
} = defineProps<{
  link: string;
  text: string;
  external?: boolean;
  active?: boolean;
}>();
</script>

<template>
  <a
    v-if="external"
    :href="link"
    class="link"
    :class="{ 'text-link-fg': !active, 'text-primary': active }"
    target="_blank"
    rel="noopener noreferrer"
  >
    {{ text }}
  </a>
  <NuxtLink
    v-else
    :to="link"
    class="link"
    :class="{ 'text-link-fg': !active, 'text-primary': active }"
  >
    {{ text }}
  </NuxtLink>
</template>

<style>
@reference "../assets/css/main.css";

.link {
  @apply font-bold outline-none
    hover:text-primary focus-visible:text-primary focus-visible:underline
    transition-colors;
}
</style>

// src/app/header/link/link.component.ts
import { Component, computed, input } from '@angular/core'
import { RouterLink } from '@angular/router'

@Component({
  selector: 'pf-link',
  imports: [
    RouterLink,
  ],
  template: `
    @if (!isExternal()) {
      <a
        class="font-ui font-bold text-neutral-700 text-2xl hover:text-frosted-blue-300 transition select-none active:text-frosted-blue-300"
        [routerLink]="link()"
      >
        <ng-content></ng-content>
      </a>
    } @else if (isExternal()) {
      <a
        class="font-ui font-bold text-neutral-700 text-2xl hover:text-frosted-blue-300 transition select-none active:text-frosted-blue-300"
        href="{{link()}}"
        target="_blank"
        rel="noopener noreferrer"
      >
        <ng-content></ng-content>
      </a>
    }
  `,
})
export class Link {
  link = input.required<string>()
  isExternal = computed(() => this.link().startsWith('http'))
}
